### ISSUE TITLE
Dependency on libre2.9.dylib

### ISSUE THREAD

**Issue by DmitryNaumov** [einari/Grpc.Core.M1#2]
I'm trying to use package on M1 and still have problems
When I try to run a program it fails with

Unhandled exception. System.IO.IOException: Error loading native library "/Users/dmitry-naumov/Work/dotnet-sdk/arti
facts/bin/Example/debug/runtimes/osx-arm64/native/libgrpc_csharp_ext.arm64.dylib".
   at Grpc.Core.Internal.UnmanagedLibrary..ctor(String[] libraryPathAlternatives)
   at Grpc.Core.Internal.NativeExtension.LoadNativeMethodsUsingExplicitLoad()
   at Grpc.Core.Internal.NativeExtension.LoadNativeMethods()
   at Grpc.Core.Internal.NativeExtension..ctor()
   at Grpc.Core.Internal.NativeExtension.Get()

I've tried to investigate the issue, how dynlib loading works on MacOS and it seems like there is a dependency on libre2.9.dylib (at least otool says that) and I didn't find it on my machine and I don't understand where to get it.

**Comment by Bluezen** [comment]
Hello, I believe you’re using either version `2.44.0` or `2.46.6` of the package, correct ?
I encountered the same problem and I’m trying to resolve it by building the latest version `2.46.7` and releasing a new update.
In the meantime, you should be able to build without issues by referencing version `2.41.0` instead.

**Comment by Bluezen** [comment]
The issue with the dylib embedded in both versions 2.44.0 and 2.46.6 might be due to how the CMake commands have been configured. 
According to the README, you should build like this:
```
cmake ../../ -DBUILD_SHARED_LIBS=ON
make
```
but when examining the `build_artifact_csharp.sh` [script](https://github.com/grpc/grpc/blob/v1.46.x/tools/run_tests/artifacts/build_artifact_csharp.sh) we should be doing
```
cmake -DCMAKE_BUILD_TYPE=RelWithDebInfo \
      -DgRPC_BACKWARDS_COMPATIBILITY_MODE=ON \
      -DgRPC_BUILD_TESTS=OFF \
      -DgRPC_XDS_USER_AGENT_IS_CSHARP=ON \
      ../..

make grpc_csharp_ext
```
I believe the issue may be using `﻿-DBUILD_SHARED_LIBS=ON` flag in `CMake` and not specifying `﻿grpc_csharp_ext` for `Make`: the resulting ﻿l`ibgrpc_csharp_ext.dylib` seems to load its dependencies as shared libraries, which is causing the current issue.

It appears we need the C# extension as a shared lib (dylib file) built against a gRPC Core lib as a single statically-linked `libgrpc.a` file with all its dependencies embedded.

**Comment by einari** [comment]
Version [2.46.7](https://www.nuget.org/packages/Contrib.Grpc.Core.M1/2.46.7) is now released. 
Thanks @Bluezen for your contribution to this.

Closing issue.
